ALTER TABLE reports DROP INDEX IF EXISTS idx_ip;
ALTER TABLE reports DROP INDEX IF EXISTS idx_geo;
ALTER TABLE reports DROP INDEX IF EXISTS idx_platform;

ALTER TABLE reports DROP COLUMN IF EXISTS platform;
ALTER TABLE reports DROP COLUMN IF EXISTS ip;
ALTER TABLE reports DROP COLUMN IF EXISTS longitude;
ALTER TABLE reports DROP COLUMN IF EXISTS latitude;